### ISSUE TITLE
blockcmp 함수 코드 작성

### ISSUE THREAD

**Issue by SoYooooon** [YeonGuKang/Assignment2#26]
void blockcmp(void)
{
	filestat1();
	int b_text1 = (int)buf.st_blocks;

	filestat2();
	int b_text2 = (int)buf.st_blocks;

	if (b_text1>b_text2) printf("text1 has more blocks\n");
	else if (b_text1<b_text2) printf("text2 has more blocks\n");
	else printf("Same blocks\n");

	return;
}

**Comment by SoYooooon** [comment]
<수정본>

 void blockcmp(void)
{
	printf("block compare\n");

	if ((int)stat1.st_blocks>(int)stat2.st_blocks) printf("text1 is bigger\n");
	else if ((int)stat1.st_blocks<(int)stat2.st_blocks) printf("text2 is bigger\n");
	else printf("blocks are equal\n");

	return;
}

**Comment by YeonGuKang** [comment]
어허.... 그런거군요? 감사합니다. ㅎㅎㅎ

**Comment by BitnaKeum** [comment]
아하 어떻게 하는지 궁금했는데 이렇게 하는거군요!
