### ISSUE TITLE
blockcmp 함수 코드 리뷰

### ISSUE THREAD

**Issue by SoYooooon** [YeonGuKang/Assignment2#30]
<코드의 주석으로 대체합니다.>

void blockcmp(void)
{
	filestat1(); // 파일1의 정보를 불러옴(filestat1 함수를 이용)
	int b_text1 = (int)buf.st_blocks; // 파일1의 블럭수를 b_text1 변수에 저장함

	filestat2(); // 파일2의 정보를 불러옴
	int b_text2 = (int)buf.st_blocks; // 파일2의 블럭수를 b_text2 변수에 저장함

	if (b_text1>b_text2) printf("text1 has more blocks\n"); // 파일1의 블럭수가 더 많을 경우
	else if (b_text1<b_text2) printf("text2 has more blocks\n"); // 파일2의 블럭수가 더 많을 경우
	else printf("Same blocks\n"); // 같을 경우

	return;
}

**Comment by SoYooooon** [comment]
<코드 수정본의 주석으로 대체합니다.>

void blockcmp(void)
{
	printf("block compare\n");

	if ((int)stat1.st_blocks>(int)stat2.st_blocks) printf("text1 is bigger\n"); // 파일1의 블럭수가 더 많을 경우
	else if ((int)stat1.st_blocks<(int)stat2.st_blocks) printf("text2 is bigger\n"); // 파일2의 블럭수가 더 많을 경우
	else printf("blocks are equal\n"); // 같을 경우

	return;
}

**Comment by YeonGuKang** [comment]
어허.... 그런거군요? 감사합니다. ㅎㅎㅎ 잘하시네여 잘부탁드립니다. 감사합니다 ㅎㅎ 또 감사합니다

**Comment by BitnaKeum** [comment]
아하 어떻게 하는지 궁금했는데 이렇게 하는거군요! 윗분 감사함이 좀 과하시네요.
