### ISSUE TITLE
stat() 함수 조사

### ISSUE THREAD

**Issue by BitNaKm** [YeonGuKang/Assignment2#31]
stat 구조체의 field =>

struct stat {
           dev_t     st_dev;         /* 장치파일의 위치 및 여부 device id */

           ino_t     st_ino;         /* 파일의 inode 번호 */

           mode_t    st_mode;        /* file permission 정보 */

           nlink_t   st_nlink;       /* 하드링크의 갯수 */

           uid_t     st_uid;         /* user id */

           gid_t     st_gid;         /* group id */

           dev_t     st_rdev;        /* 장치파일(inode)를 기술 */

           off_t     st_size;        /* 해당 파일의 총 크기*/

           blksize_t st_blksize;     /* 효율적인 I/O 파일 시스템 위한 블럭 사이즈*/

           blkcnt_t  st_blocks;      /* 할당된 블럭 사이즈 */

       };

**Comment by BitNaKm** [comment]
int stat(const char* path, struct stat* buf);

const char* path는 파일의 경로를 나타내고,
struct stat* buf는 파일의 정보가 들어오는 구조체 포인터이다.

stat() 함수를 사용해 파일의 정보를 가져올 수 있다.

**Comment by YeonGuKang** [comment]
잘하셨습니다.

**Comment by SoYooooon** [comment]
어렵네요..
