### ISSUE TITLE
stat() 함수 코드 작성

### ISSUE THREAD

**Issue by BitNaKm** [YeonGuKang/Assignment2#32]
#include <sys/types.h>
 #include <sys/stat.h>
 #include <unistd.h>

함수가 선언되어 있는 헤더파일을 선언한다.

**Comment by BitNaKm** [comment]
#include <sys/types.h>
 #include <sys/stat.h>
 #include <unistd.h>

int main()
{
        struct stat buf;
        stat("text", &buf);
}


이와 같은 방식으로 코드를 작성해 사용한다.

**Comment by YeonGuKang** [comment]
잘하셨습니다. 오호 그렇군요~

**Comment by SoYooooon** [comment]
잘 봤습니다!
