### ISSUE TITLE
그 외의 함수 조사

### ISSUE THREAD

**Issue by BitNaKm** [YeonGuKang/Assignment2#33]
stat()함수와 비슷한 역할을 하는 함수로 fstat(), lstat() 이 있다.

**Comment by YeonGuKang** [comment]
잘하셨습니다. 오호 그렇군요~ 감사합니다. 사랑합니다.

**Comment by SoYooooon** [comment]
잘봤습니다. 나도 사랑할게요......ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ
