### ISSUE TITLE
localtime 함수 조사

### ISSUE THREAD

**Issue by BitNaKm** [YeonGuKang/Assignment2#34]
struct tm * localtime(const time_t* timep);

=> timep가 가리키는 time_t의 값을 이용하여 tm 구조체를 초기화하고 포인터를 리턴함으로써 시간정보를 얻을 수 있다.

**Comment by BitNaKm** [comment]
struct tm
{
  int tm_sec;			/* Seconds.	[0-60] (1 leap second) */
  int tm_min;			/* Minutes.	[0-59] */
  int tm_hour;			/* Hours.	[0-23] */
  int tm_mday;			/* Day.		[1-31] */
  int tm_mon;			/* Month.	[0-11] */
  int tm_year;			/* Year	- 1900.  */
  int tm_wday;			/* Day of week.	[0-6] */
  int tm_yday;			/* Days in year.[0-365]	*/
  int tm_isdst;			/* DST.		[-1/0/1]*/

#ifdef	__USE_BSD
  long int tm_gmtoff;		/* Seconds east of UTC.  */
  __const char *tm_zone;	/* Timezone abbreviation.  */
#else
  long int __tm_gmtoff;		/* Seconds east of UTC.  */
  __const char *__tm_zone;	/* Timezone abbreviation.  */
#endif
};

**Comment by BitNaKm** [comment]
#include <time.h> 헤더파일에 선언되어 있다.

**Comment by BitNaKm** [comment]
시간은 지역 시간 기준으로 표시된다.

**Comment by SoYooooon** [comment]
그렇구나

**Comment by YeonGuKang** [comment]
잘하셨습니다. 오호 그렇군요~ 감사합니다. 사랑합니다. 또 사랑합니다.
