### ISSUE TITLE
localtime 함수 코드 작성

### ISSUE THREAD

**Issue by BitNaKm** [YeonGuKang/Assignment2#35]
#include <time.h>

int main()
{
           struct stat buf;
           struct tm* time;
           time = localtime(&buf.st_mtime);
}

이와 같은 방식으로 작성하여 시간 정보를 얻을 수 있다.

**Comment by SoYooooon** [comment]
굿잡

**Comment by YeonGuKang** [comment]
잘하셨습니다. 오호 그렇군요~ 감사합니다. 사랑합니다. 또 사랑합니다. 굿잡입니다.
