### ISSUE TITLE
파일 수정 날짜 비교에 대한 코드구현

### ISSUE THREAD

**Issue by YeonGuKang** [YeonGuKang/Assignment2#44]
void datecmp(void)
{

if((time1->tm_mon+1)>(time2->tm_mon+1))
            printf("text2 is early\n");
    else if ((time1->tm_mon+1)<(time2->tm_mon+1))
            printf("text1 is early\n");
    else if ((time1->tm_mon+1)==(time2->tm_mon+1))
    {
            if((time1->tm_mday)>(time2->tm_mday))
                     printf("text2 is early\n");
            else if ((time1->tm_mday)<(time2->tm_mday))
                     printf("text1 is early\n");
            else
                     printf("same date\n");

    }
}
위의 정보를 토대로 구현한 코드이다.

**Comment by BitnaKeum** [comment]
코드가 깔끔하군요.

**Comment by SoYooooon** [comment]
다 완성되었네요!
