### ISSUE TITLE
파일 수정 시간 비교에 대한 코드

### ISSUE THREAD

**Issue by YeonGuKang** [YeonGuKang/Assignment2#45]
void timecmp(void)
{
	printf("time compare\n");
	if((time1->tm_hour)>(time2->tm_hour))
                printf("text2 is early\n");
        else if ((time1->tm_hour)<(time2->tm_hour))
                printf("text1 is early\n");
        else if ((time1->tm_hour)==(time2->tm_hour))
        {
                if((time1->tm_min)>(time2->tm_min))
                         printf("text2 is early\n");
                else if ((time1->tm_min)<(time2->tm_min))
                         printf("text1 is early\n");
                else
                         printf("same time\n");

	 }
}

**Comment by BitnaKeum** [comment]
코드가 깔끔하군요.

**Comment by SoYooooon** [comment]
if 조건문을 사용하셨군요!
