### ISSUE TITLE
stat 함수의 코드 리뷰

### ISSUE THREAD

**Issue by BitnaKeum** [YeonGuKang/Assignment2#46]
void filestat1(void)    // text1의 정보를 가져오는 함수
{ 
       	stat("text1", &stat1);      // text1의 정보가 stat1에 저장됨
} 

void filestat2(void)    // text2의 정보를 가져오는 함수
{ 
         stat("text2", &stat2);     // text2의 정보가 stat2에 저장됨
}

**Comment by BitnaKeum** [comment]
주석을 통해 리뷰를 하였습니다.

**Comment by YeonGuKang** [comment]
잘했습니다 ㅎㅎ.

**Comment by SoYooooon** [comment]
멋지네요
