### ISSUE TITLE
파일 수정 날짜 비교에 대한 함수 리뷰

### ISSUE THREAD

**Issue by YeonGuKang** [YeonGuKang/Assignment2#47]
void datecmp(void)
{

if((time1->tm_mon+1)>(time2->tm_mon+1))      //만약 text1 변수의 월이 더 클때 text2가 더빠름 
            printf("text2 is early\n");
    else if ((time1->tm_mon+1)<(time2->tm_mon+1))     //만약 text2 변수의 월이 더 클때 text1가 더빠름 
            printf("text1 is early\n");
    else if ((time1->tm_mon+1)==(time2->tm_mon+1))    //만약 같을때
    {
            if((time1->tm_mday)>(time2->tm_mday))     //만약 text2 변수의 일이 더 클때 text1가 더빠름
                     printf("text2 is early\n");
            else if ((time1->tm_mday)<(time2->tm_mday))     //만약 text1 변수의 월이 더 클때 text2가 더빠름
                     printf("text1 is early\n");
            else
                     printf("same date\n");     // 만약 일마저 같을 때 같음

    }
}
리뷰이다.

**Comment by BitnaKeum** [comment]
리뷰가 참 간결하고 멋지십니다.

**Comment by SoYooooon** [comment]
리뷰네요
