### ISSUE TITLE
localtime 함수의 코드 리뷰

### ISSUE THREAD

**Issue by BitnaKeum** [YeonGuKang/Assignment2#48]
void filetime1(void)    // text1의 시간정보를 가져오는 함수
{ 
	time1 = localtime(&stat1.st_mtime);      // stat1.st_mtime의 값을 이용하여 time1에 시간정보가 담긴다.
} 
  
void filetime2(void)    // text2의 시간정보를 가져오는 함수 
{ 
	time2 = localtime(&stat2.st_mtime);     // stat1.st_mtime의 값을 이용하여 time1에 시간정보가 담긴다.
}

**Comment by BitnaKeum** [comment]
주석을 통해 리뷰 하였습니다.

**Comment by YeonGuKang** [comment]
잘했습니다 ㅎㅎ. 힘들다....

**Comment by SoYooooon** [comment]
보기 쉽네요.
