### ISSUE TITLE
파일 수정 시간 비교에 대한 코드리뷰

### ISSUE THREAD

**Issue by YeonGuKang** [YeonGuKang/Assignment2#49]
리뷰이다.

void timecmp(void)
{
printf("time compare\n");
if((time1->tm_hour)>(time2->tm_hour))     //만약 text1 의 시간이 더 크면 text2가 더 빠르다.
printf("text2 is early\n");
else if ((time1->tm_hour)<(time2->tm_hour))     //만약 text2 의 시간이 더 크면 text1가 더 빠르다.
printf("text1 is early\n");
else if ((time1->tm_hour)==(time2->tm_hour))     //만약 시간이 같으면 실행
{
if((time1->tm_min)>(time2->tm_min))      //만약 text1 의 분이 더 크면 text2가 더 빠르다.
printf("text2 is early\n");
else if ((time1->tm_min)<(time2->tm_min))   //만약 text2 의 분이 더 크면 text1가 더 빠르다.
printf("text1 is early\n");
else
printf("same time\n");    // 시/분 모두 같으면 같다.

 }
}

**Comment by BitnaKeum** [comment]
이 어려운 코드를 구현하시다니! 아주 멋지십니다.

**Comment by SoYooooon** [comment]
그렇군요.
