### ISSUE TITLE
파일 수정 날짜 비교 함수에 대한 조사.

### ISSUE THREAD

**Issue by YeonGuKang** [YeonGuKang/Assignment2#6]

**Comment by YeonGuKang** [comment]
파일 수정 날짜를 비교하기 위해서 stat, localtime 구조체를 이용한다.

파일의 정보를 구조체 변수에 저장을 하여 구조체를 이루고있는 요소들로 날짜 비교를 한다.

**Comment by YeonGuKang** [comment]
void datecmp(void)
{

	if((time1->tm_mon+1)>(time2->tm_mon+1))
                printf("text2 is early\n");
        else if ((time1->tm_mon+1)<(time2->tm_mon+1))
                printf("text1 is early\n");
        else if ((time1->tm_mon+1)==(time2->tm_mon+1))
        {
                if((time1->tm_mday)>(time2->tm_mday))
                         printf("text2 is early\n");
                else if ((time1->tm_mday)<(time2->tm_mday))
                         printf("text1 is early\n");
                else
                         printf("same date\n");

        }


}
위의 정보를 토대로 구현한 코드이다.

**Comment by BitnaKeum** [comment]
아하 어떻게 하는지 궁금했는데 이렇게 하는거군요!

**Comment by SoYooooon** [comment]
그렇군요
